language: node_js
node_js: 8
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- npm install -g svgexport
script:
- npm run build:prod
- mkdir -p dist/assets/png@{1..2}x
- |
  for f in dist/assets/svg/*.svg
  do
    img_name=$(echo $f | sed 's/\.svg$//g;s/^.\{16\}//g')
    for n in {1..2}
    do
      svgexport \
        "dist/assets/svg/$img_name.svg" \
        "dist/assets/png@${n}x/$img_name.png" \
        "100%" \
        "${n}00:" \
        &
    done
  done
  wait
- |
  pushd dist/assets/
  for t in svg png@{1..2}x
  do
    tar czvf "a3-kyiv-transport-icons-${t}.tar.gz" "${t}/"
    zip -r "a3-kyiv-transport-icons-${t}.zip" "${t}/"
  done
  popd
- |
  pushd dist/assets/
  tar czvf "a3-kyiv-transport-icons.tar.gz" {svg,png@{1..2}x}
  zip -r "a3-kyiv-transport-icons.zip" {svg,png@{1..2}x}
  popd
deploy:
- provider: pages
  allow-empty-commit: true
  # FIXME: uncomment following line once ready
  # fqdn: icons.a3.kyiv.ua
  github-token: &gh-token
    secure: "C7NFWC4XmFyKSoAOFYkayN23VA3BfbZoPovT2SdhUzixFm6p1rADYxTFrTUVUb4HpCDQwvXmcwx/xmSKx8SrTAdvxyvJzGaCci31OxFdQnJdPpUXqHbsF0OGAl557iSNpbQA1gaBupn/d3CdZjn1ZwSWIMXpE5b3NMJMRj7/5EVTFG0k0qLbPdQrfdzNCecC/p2ulb0eV0dFd8jbPzUvyEqDRHj+2ikZu2/BJlkktY4I5AnP/04acfllVaJIkTkK411M2RSF2n6rnv9KVMpyrqzH5BrcJzJAM9VaVQOXDFW8lHy47BfukSGBymanJvTVdG/fBNEzg4OQwDf2zD9rOXMcKm3kVIJsxEUDnUcRGOWgmB/Yu+0TqGfOdfn0I5ya9RapufrWrmDJ/dItamyXBELacSoWsf+49bUISwHUQvncgnjgJpLppRmBpAF2cMm2hl2QVKpBjSqzss3RUh4ykCsPkaF7IeScz2hudL44Auo7j5wnDtAAE5mLMCacKbWkwul1Wjt4PFu3yLq4DYIX3psaJLtJkdBQHa4PDFqlXy1XpOZJIZQVTndtMnMtIPL37VChEehawIOdeDHqvEFujMuMMSLORUdrb+hzzyHvlRqbhuPEyIGoRGuDC0v/oMJRJw4uXefzeInjZZmtLo0MTyDiRB931HR1ijbNEQXAF3M="
  keep-history: true
  local-dir: dist
  skip-cleanup: true
  target-branch: gh-pages
- provider: releases
  api_key: *gh-token
  file_glob: true
  file: dist/assets/*.{tar.gz,zip}
  skip_cleanup: true
  on:
    tags: true
